### PR TITLE
feat(tvos): Detect long up/down/left/right arrow press

### PR DESCRIPTION
**Pull request by cywong-amino**
Copying the commit from https://github.com/react-native-tvos/react-native-tvos/commit/55bbf462bc591832051f689647ecef4a2b9e2a69

### CODE REVIEW

**Review by CHaNGeTe — APPROVED** [review]

**Review by mmehtonen-24i — CHANGES_REQUESTED** [review]
Describe all these changes on README-24i.md file. See https://github.com/24i/react-native-tvos/blob/24i-fork-branch/README-24i.md. Rebase with that branch in order to get the latest changes (I just pushed a change on that file)

**Comment by mmehtonen-24i** [comment]
Changes on [ReactAndroidHWInputDeviceHelper.java](https://github.com/react-native-tvos/react-native-tvos/commit/55bbf462bc591832051f689647ecef4a2b9e2a69#diff-e13ce49803560a430e32e90af1dbfb48764f175ed9b78ac5b4f05c159f536e9a) are not copied. Is this intentional?

**Comment by mmehtonen-24i** [comment]
Having meetings, taking a closer look after that ->

**Comment by cywong-amino** [comment]
The file in our branch differs a lot from the one where the fix is made. It will require more changes to also apply the android fix. As we don't need to support the android side I'd suggest skipping it.

**Review by mmehtonen-24i — APPROVED** [review]
👍

**Comment by mmehtonen-24i** [comment]
> The file in our branch differs a lot from the one where the fix is made. It will require more changes to also apply the android fix. As we don't need to support the android side I'd suggest skipping it.

I agree. We are likely to update react-native-tvos before adding a support on Android TV. Working on this now would be probably a lost work.

**Pull request merged**
